// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: token.proto

package com.google.appinventor.server.tokens;

public final class TokenProto {
  private TokenProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface tokenOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tokens.token)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .tokens.token.CommandType command = 1;</code>
     */
    boolean hasCommand();
    /**
     * <code>required .tokens.token.CommandType command = 1;</code>
     */
    com.google.appinventor.server.tokens.TokenProto.token.CommandType getCommand();

    /**
     * <code>optional uint64 ts = 2;</code>
     *
     * <pre>
     * Current timestamp (as a Java time, millis since 1970)
     * </pre>
     */
    boolean hasTs();
    /**
     * <code>optional uint64 ts = 2;</code>
     *
     * <pre>
     * Current timestamp (as a Java time, millis since 1970)
     * </pre>
     */
    long getTs();

    /**
     * <code>optional string uuid = 3;</code>
     *
     * <pre>
     * userId (which is usually a uuid, but always a string)
     * </pre>
     */
    boolean hasUuid();
    /**
     * <code>optional string uuid = 3;</code>
     *
     * <pre>
     * userId (which is usually a uuid, but always a string)
     * </pre>
     */
    java.lang.String getUuid();
    /**
     * <code>optional string uuid = 3;</code>
     *
     * <pre>
     * userId (which is usually a uuid, but always a string)
     * </pre>
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <code>optional uint64 projectid = 4;</code>
     *
     * <pre>
     * When showing a project, this is its ID, not used for SSOLOGIN
     * </pre>
     */
    boolean hasProjectid();
    /**
     * <code>optional uint64 projectid = 4;</code>
     *
     * <pre>
     * When showing a project, this is its ID, not used for SSOLOGIN
     * </pre>
     */
    long getProjectid();

    /**
     * <code>optional string name = 5;</code>
     *
     * <pre>
     * this argument also is used in create project as the
     * source project to copy
     * </pre>
     */
    boolean hasName();
    /**
     * <code>optional string name = 5;</code>
     *
     * <pre>
     * this argument also is used in create project as the
     * source project to copy
     * </pre>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 5;</code>
     *
     * <pre>
     * this argument also is used in create project as the
     * source project to copy
     * </pre>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional uint64 oneProjectId = 6;</code>
     *
     * <pre>
     * non-zero to open a specific project
     * </pre>
     */
    boolean hasOneProjectId();
    /**
     * <code>optional uint64 oneProjectId = 6;</code>
     *
     * <pre>
     * non-zero to open a specific project
     * </pre>
     */
    long getOneProjectId();

    /**
     * <code>optional bool readOnly = 20;</code>
     */
    boolean hasReadOnly();
    /**
     * <code>optional bool readOnly = 20;</code>
     */
    boolean getReadOnly();

    /**
     * <code>optional uint64 duedate = 21;</code>
     *
     * <pre>
     * Date when the project is due 0 = never due
     * </pre>
     */
    boolean hasDuedate();
    /**
     * <code>optional uint64 duedate = 21;</code>
     *
     * <pre>
     * Date when the project is due 0 = never due
     * </pre>
     */
    long getDuedate();

    /**
     * <code>optional string displayprojectname = 22;</code>
     *
     * <pre>
     * or not an assignment
     * </pre>
     */
    boolean hasDisplayprojectname();
    /**
     * <code>optional string displayprojectname = 22;</code>
     *
     * <pre>
     * or not an assignment
     * </pre>
     */
    java.lang.String getDisplayprojectname();
    /**
     * <code>optional string displayprojectname = 22;</code>
     *
     * <pre>
     * or not an assignment
     * </pre>
     */
    com.google.protobuf.ByteString
        getDisplayprojectnameBytes();

    /**
     * <code>optional string displayaccountname = 23;</code>
     *
     * <pre>
     * User name to display instead of email address
     * </pre>
     */
    boolean hasDisplayaccountname();
    /**
     * <code>optional string displayaccountname = 23;</code>
     *
     * <pre>
     * User name to display instead of email address
     * </pre>
     */
    java.lang.String getDisplayaccountname();
    /**
     * <code>optional string displayaccountname = 23;</code>
     *
     * <pre>
     * User name to display instead of email address
     * </pre>
     */
    com.google.protobuf.ByteString
        getDisplayaccountnameBytes();

    /**
     * <code>optional string backpackid = 24;</code>
     *
     * <pre>
     * accounts created by the HK portal have "ugly" account
     * names, so they provide something "better" to display instead
     * </pre>
     */
    boolean hasBackpackid();
    /**
     * <code>optional string backpackid = 24;</code>
     *
     * <pre>
     * accounts created by the HK portal have "ugly" account
     * names, so they provide something "better" to display instead
     * </pre>
     */
    java.lang.String getBackpackid();
    /**
     * <code>optional string backpackid = 24;</code>
     *
     * <pre>
     * accounts created by the HK portal have "ugly" account
     * names, so they provide something "better" to display instead
     * </pre>
     */
    com.google.protobuf.ByteString
        getBackpackidBytes();
  }
  /**
   * Protobuf type {@code tokens.token}
   */
  public static final class token extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tokens.token)
      tokenOrBuilder {
    // Use token.newBuilder() to construct.
    private token(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private token(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final token defaultInstance;
    public static token getDefaultInstance() {
      return defaultInstance;
    }

    public token getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private token(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.google.appinventor.server.tokens.TokenProto.token.CommandType value = com.google.appinventor.server.tokens.TokenProto.token.CommandType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                command_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              ts_ = input.readUInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              uuid_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              projectid_ = input.readUInt64();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              name_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              oneProjectId_ = input.readUInt64();
              break;
            }
            case 160: {
              bitField0_ |= 0x00000040;
              readOnly_ = input.readBool();
              break;
            }
            case 168: {
              bitField0_ |= 0x00000080;
              duedate_ = input.readUInt64();
              break;
            }
            case 178: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              displayprojectname_ = bs;
              break;
            }
            case 186: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              displayaccountname_ = bs;
              break;
            }
            case 194: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000400;
              backpackid_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.appinventor.server.tokens.TokenProto.internal_static_tokens_token_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.appinventor.server.tokens.TokenProto.internal_static_tokens_token_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.appinventor.server.tokens.TokenProto.token.class, com.google.appinventor.server.tokens.TokenProto.token.Builder.class);
    }

    public static com.google.protobuf.Parser<token> PARSER =
        new com.google.protobuf.AbstractParser<token>() {
      public token parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new token(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<token> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code tokens.token.CommandType}
     */
    public enum CommandType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SSOLOGIN = 0;</code>
       */
      SSOLOGIN(0, 0),
      /**
       * <code>SHOWPROJECT = 1;</code>
       */
      SHOWPROJECT(1, 1),
      /**
       * <code>CREATEACCOUNT = 2;</code>
       */
      CREATEACCOUNT(2, 2),
      /**
       * <code>CREATEPROJECT = 3;</code>
       */
      CREATEPROJECT(3, 3),
      /**
       * <code>LOGOUT = 4;</code>
       */
      LOGOUT(4, 4),
      /**
       * <code>SSOLOGIN2 = 5;</code>
       */
      SSOLOGIN2(5, 5),
      /**
       * <code>NOOP = 20;</code>
       */
      NOOP(6, 20),
      ;

      /**
       * <code>SSOLOGIN = 0;</code>
       */
      public static final int SSOLOGIN_VALUE = 0;
      /**
       * <code>SHOWPROJECT = 1;</code>
       */
      public static final int SHOWPROJECT_VALUE = 1;
      /**
       * <code>CREATEACCOUNT = 2;</code>
       */
      public static final int CREATEACCOUNT_VALUE = 2;
      /**
       * <code>CREATEPROJECT = 3;</code>
       */
      public static final int CREATEPROJECT_VALUE = 3;
      /**
       * <code>LOGOUT = 4;</code>
       */
      public static final int LOGOUT_VALUE = 4;
      /**
       * <code>SSOLOGIN2 = 5;</code>
       */
      public static final int SSOLOGIN2_VALUE = 5;
      /**
       * <code>NOOP = 20;</code>
       */
      public static final int NOOP_VALUE = 20;


      public final int getNumber() { return value; }

      public static CommandType valueOf(int value) {
        switch (value) {
          case 0: return SSOLOGIN;
          case 1: return SHOWPROJECT;
          case 2: return CREATEACCOUNT;
          case 3: return CREATEPROJECT;
          case 4: return LOGOUT;
          case 5: return SSOLOGIN2;
          case 20: return NOOP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CommandType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
              public CommandType findValueByNumber(int number) {
                return CommandType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.google.appinventor.server.tokens.TokenProto.token.getDescriptor().getEnumTypes().get(0);
      }

      private static final CommandType[] VALUES = values();

      public static CommandType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private CommandType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tokens.token.CommandType)
    }

    private int bitField0_;
    public static final int COMMAND_FIELD_NUMBER = 1;
    private com.google.appinventor.server.tokens.TokenProto.token.CommandType command_;
    /**
     * <code>required .tokens.token.CommandType command = 1;</code>
     */
    public boolean hasCommand() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .tokens.token.CommandType command = 1;</code>
     */
    public com.google.appinventor.server.tokens.TokenProto.token.CommandType getCommand() {
      return command_;
    }

    public static final int TS_FIELD_NUMBER = 2;
    private long ts_;
    /**
     * <code>optional uint64 ts = 2;</code>
     *
     * <pre>
     * Current timestamp (as a Java time, millis since 1970)
     * </pre>
     */
    public boolean hasTs() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 ts = 2;</code>
     *
     * <pre>
     * Current timestamp (as a Java time, millis since 1970)
     * </pre>
     */
    public long getTs() {
      return ts_;
    }

    public static final int UUID_FIELD_NUMBER = 3;
    private java.lang.Object uuid_;
    /**
     * <code>optional string uuid = 3;</code>
     *
     * <pre>
     * userId (which is usually a uuid, but always a string)
     * </pre>
     */
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string uuid = 3;</code>
     *
     * <pre>
     * userId (which is usually a uuid, but always a string)
     * </pre>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uuid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string uuid = 3;</code>
     *
     * <pre>
     * userId (which is usually a uuid, but always a string)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROJECTID_FIELD_NUMBER = 4;
    private long projectid_;
    /**
     * <code>optional uint64 projectid = 4;</code>
     *
     * <pre>
     * When showing a project, this is its ID, not used for SSOLOGIN
     * </pre>
     */
    public boolean hasProjectid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint64 projectid = 4;</code>
     *
     * <pre>
     * When showing a project, this is its ID, not used for SSOLOGIN
     * </pre>
     */
    public long getProjectid() {
      return projectid_;
    }

    public static final int NAME_FIELD_NUMBER = 5;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 5;</code>
     *
     * <pre>
     * this argument also is used in create project as the
     * source project to copy
     * </pre>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string name = 5;</code>
     *
     * <pre>
     * this argument also is used in create project as the
     * source project to copy
     * </pre>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 5;</code>
     *
     * <pre>
     * this argument also is used in create project as the
     * source project to copy
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ONEPROJECTID_FIELD_NUMBER = 6;
    private long oneProjectId_;
    /**
     * <code>optional uint64 oneProjectId = 6;</code>
     *
     * <pre>
     * non-zero to open a specific project
     * </pre>
     */
    public boolean hasOneProjectId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional uint64 oneProjectId = 6;</code>
     *
     * <pre>
     * non-zero to open a specific project
     * </pre>
     */
    public long getOneProjectId() {
      return oneProjectId_;
    }

    public static final int READONLY_FIELD_NUMBER = 20;
    private boolean readOnly_;
    /**
     * <code>optional bool readOnly = 20;</code>
     */
    public boolean hasReadOnly() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bool readOnly = 20;</code>
     */
    public boolean getReadOnly() {
      return readOnly_;
    }

    public static final int DUEDATE_FIELD_NUMBER = 21;
    private long duedate_;
    /**
     * <code>optional uint64 duedate = 21;</code>
     *
     * <pre>
     * Date when the project is due 0 = never due
     * </pre>
     */
    public boolean hasDuedate() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional uint64 duedate = 21;</code>
     *
     * <pre>
     * Date when the project is due 0 = never due
     * </pre>
     */
    public long getDuedate() {
      return duedate_;
    }

    public static final int DISPLAYPROJECTNAME_FIELD_NUMBER = 22;
    private java.lang.Object displayprojectname_;
    /**
     * <code>optional string displayprojectname = 22;</code>
     *
     * <pre>
     * or not an assignment
     * </pre>
     */
    public boolean hasDisplayprojectname() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string displayprojectname = 22;</code>
     *
     * <pre>
     * or not an assignment
     * </pre>
     */
    public java.lang.String getDisplayprojectname() {
      java.lang.Object ref = displayprojectname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          displayprojectname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string displayprojectname = 22;</code>
     *
     * <pre>
     * or not an assignment
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDisplayprojectnameBytes() {
      java.lang.Object ref = displayprojectname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displayprojectname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DISPLAYACCOUNTNAME_FIELD_NUMBER = 23;
    private java.lang.Object displayaccountname_;
    /**
     * <code>optional string displayaccountname = 23;</code>
     *
     * <pre>
     * User name to display instead of email address
     * </pre>
     */
    public boolean hasDisplayaccountname() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string displayaccountname = 23;</code>
     *
     * <pre>
     * User name to display instead of email address
     * </pre>
     */
    public java.lang.String getDisplayaccountname() {
      java.lang.Object ref = displayaccountname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          displayaccountname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string displayaccountname = 23;</code>
     *
     * <pre>
     * User name to display instead of email address
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDisplayaccountnameBytes() {
      java.lang.Object ref = displayaccountname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displayaccountname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BACKPACKID_FIELD_NUMBER = 24;
    private java.lang.Object backpackid_;
    /**
     * <code>optional string backpackid = 24;</code>
     *
     * <pre>
     * accounts created by the HK portal have "ugly" account
     * names, so they provide something "better" to display instead
     * </pre>
     */
    public boolean hasBackpackid() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string backpackid = 24;</code>
     *
     * <pre>
     * accounts created by the HK portal have "ugly" account
     * names, so they provide something "better" to display instead
     * </pre>
     */
    public java.lang.String getBackpackid() {
      java.lang.Object ref = backpackid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          backpackid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string backpackid = 24;</code>
     *
     * <pre>
     * accounts created by the HK portal have "ugly" account
     * names, so they provide something "better" to display instead
     * </pre>
     */
    public com.google.protobuf.ByteString
        getBackpackidBytes() {
      java.lang.Object ref = backpackid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        backpackid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      command_ = com.google.appinventor.server.tokens.TokenProto.token.CommandType.SSOLOGIN;
      ts_ = 0L;
      uuid_ = "";
      projectid_ = 0L;
      name_ = "";
      oneProjectId_ = 0L;
      readOnly_ = false;
      duedate_ = 0L;
      displayprojectname_ = "";
      displayaccountname_ = "";
      backpackid_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCommand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, command_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, ts_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getUuidBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(4, projectid_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt64(6, oneProjectId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(20, readOnly_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeUInt64(21, duedate_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(22, getDisplayprojectnameBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(23, getDisplayaccountnameBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(24, getBackpackidBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, command_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, ts_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getUuidBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, projectid_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, oneProjectId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(20, readOnly_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(21, duedate_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(22, getDisplayprojectnameBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(23, getDisplayaccountnameBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(24, getBackpackidBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.appinventor.server.tokens.TokenProto.token parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.appinventor.server.tokens.TokenProto.token parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.appinventor.server.tokens.TokenProto.token parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.appinventor.server.tokens.TokenProto.token parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.appinventor.server.tokens.TokenProto.token parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.appinventor.server.tokens.TokenProto.token parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.appinventor.server.tokens.TokenProto.token parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.appinventor.server.tokens.TokenProto.token parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.appinventor.server.tokens.TokenProto.token parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.appinventor.server.tokens.TokenProto.token parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.appinventor.server.tokens.TokenProto.token prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tokens.token}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tokens.token)
        com.google.appinventor.server.tokens.TokenProto.tokenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.appinventor.server.tokens.TokenProto.internal_static_tokens_token_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.appinventor.server.tokens.TokenProto.internal_static_tokens_token_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.appinventor.server.tokens.TokenProto.token.class, com.google.appinventor.server.tokens.TokenProto.token.Builder.class);
      }

      // Construct using com.google.appinventor.server.tokens.TokenProto.token.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        command_ = com.google.appinventor.server.tokens.TokenProto.token.CommandType.SSOLOGIN;
        bitField0_ = (bitField0_ & ~0x00000001);
        ts_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        uuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        projectid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        oneProjectId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        readOnly_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        duedate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        displayprojectname_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        displayaccountname_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        backpackid_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.appinventor.server.tokens.TokenProto.internal_static_tokens_token_descriptor;
      }

      public com.google.appinventor.server.tokens.TokenProto.token getDefaultInstanceForType() {
        return com.google.appinventor.server.tokens.TokenProto.token.getDefaultInstance();
      }

      public com.google.appinventor.server.tokens.TokenProto.token build() {
        com.google.appinventor.server.tokens.TokenProto.token result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.appinventor.server.tokens.TokenProto.token buildPartial() {
        com.google.appinventor.server.tokens.TokenProto.token result = new com.google.appinventor.server.tokens.TokenProto.token(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.command_ = command_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ts_ = ts_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.uuid_ = uuid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.projectid_ = projectid_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.oneProjectId_ = oneProjectId_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.readOnly_ = readOnly_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.duedate_ = duedate_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.displayprojectname_ = displayprojectname_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.displayaccountname_ = displayaccountname_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.backpackid_ = backpackid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.appinventor.server.tokens.TokenProto.token) {
          return mergeFrom((com.google.appinventor.server.tokens.TokenProto.token)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.appinventor.server.tokens.TokenProto.token other) {
        if (other == com.google.appinventor.server.tokens.TokenProto.token.getDefaultInstance()) return this;
        if (other.hasCommand()) {
          setCommand(other.getCommand());
        }
        if (other.hasTs()) {
          setTs(other.getTs());
        }
        if (other.hasUuid()) {
          bitField0_ |= 0x00000004;
          uuid_ = other.uuid_;
          onChanged();
        }
        if (other.hasProjectid()) {
          setProjectid(other.getProjectid());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000010;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasOneProjectId()) {
          setOneProjectId(other.getOneProjectId());
        }
        if (other.hasReadOnly()) {
          setReadOnly(other.getReadOnly());
        }
        if (other.hasDuedate()) {
          setDuedate(other.getDuedate());
        }
        if (other.hasDisplayprojectname()) {
          bitField0_ |= 0x00000100;
          displayprojectname_ = other.displayprojectname_;
          onChanged();
        }
        if (other.hasDisplayaccountname()) {
          bitField0_ |= 0x00000200;
          displayaccountname_ = other.displayaccountname_;
          onChanged();
        }
        if (other.hasBackpackid()) {
          bitField0_ |= 0x00000400;
          backpackid_ = other.backpackid_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCommand()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.appinventor.server.tokens.TokenProto.token parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.appinventor.server.tokens.TokenProto.token) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.appinventor.server.tokens.TokenProto.token.CommandType command_ = com.google.appinventor.server.tokens.TokenProto.token.CommandType.SSOLOGIN;
      /**
       * <code>required .tokens.token.CommandType command = 1;</code>
       */
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .tokens.token.CommandType command = 1;</code>
       */
      public com.google.appinventor.server.tokens.TokenProto.token.CommandType getCommand() {
        return command_;
      }
      /**
       * <code>required .tokens.token.CommandType command = 1;</code>
       */
      public Builder setCommand(com.google.appinventor.server.tokens.TokenProto.token.CommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .tokens.token.CommandType command = 1;</code>
       */
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000001);
        command_ = com.google.appinventor.server.tokens.TokenProto.token.CommandType.SSOLOGIN;
        onChanged();
        return this;
      }

      private long ts_ ;
      /**
       * <code>optional uint64 ts = 2;</code>
       *
       * <pre>
       * Current timestamp (as a Java time, millis since 1970)
       * </pre>
       */
      public boolean hasTs() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint64 ts = 2;</code>
       *
       * <pre>
       * Current timestamp (as a Java time, millis since 1970)
       * </pre>
       */
      public long getTs() {
        return ts_;
      }
      /**
       * <code>optional uint64 ts = 2;</code>
       *
       * <pre>
       * Current timestamp (as a Java time, millis since 1970)
       * </pre>
       */
      public Builder setTs(long value) {
        bitField0_ |= 0x00000002;
        ts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 ts = 2;</code>
       *
       * <pre>
       * Current timestamp (as a Java time, millis since 1970)
       * </pre>
       */
      public Builder clearTs() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ts_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object uuid_ = "";
      /**
       * <code>optional string uuid = 3;</code>
       *
       * <pre>
       * userId (which is usually a uuid, but always a string)
       * </pre>
       */
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string uuid = 3;</code>
       *
       * <pre>
       * userId (which is usually a uuid, but always a string)
       * </pre>
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uuid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string uuid = 3;</code>
       *
       * <pre>
       * userId (which is usually a uuid, but always a string)
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string uuid = 3;</code>
       *
       * <pre>
       * userId (which is usually a uuid, but always a string)
       * </pre>
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 3;</code>
       *
       * <pre>
       * userId (which is usually a uuid, but always a string)
       * </pre>
       */
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 3;</code>
       *
       * <pre>
       * userId (which is usually a uuid, but always a string)
       * </pre>
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        uuid_ = value;
        onChanged();
        return this;
      }

      private long projectid_ ;
      /**
       * <code>optional uint64 projectid = 4;</code>
       *
       * <pre>
       * When showing a project, this is its ID, not used for SSOLOGIN
       * </pre>
       */
      public boolean hasProjectid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint64 projectid = 4;</code>
       *
       * <pre>
       * When showing a project, this is its ID, not used for SSOLOGIN
       * </pre>
       */
      public long getProjectid() {
        return projectid_;
      }
      /**
       * <code>optional uint64 projectid = 4;</code>
       *
       * <pre>
       * When showing a project, this is its ID, not used for SSOLOGIN
       * </pre>
       */
      public Builder setProjectid(long value) {
        bitField0_ |= 0x00000008;
        projectid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 projectid = 4;</code>
       *
       * <pre>
       * When showing a project, this is its ID, not used for SSOLOGIN
       * </pre>
       */
      public Builder clearProjectid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        projectid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 5;</code>
       *
       * <pre>
       * this argument also is used in create project as the
       * source project to copy
       * </pre>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string name = 5;</code>
       *
       * <pre>
       * this argument also is used in create project as the
       * source project to copy
       * </pre>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 5;</code>
       *
       * <pre>
       * this argument also is used in create project as the
       * source project to copy
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 5;</code>
       *
       * <pre>
       * this argument also is used in create project as the
       * source project to copy
       * </pre>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 5;</code>
       *
       * <pre>
       * this argument also is used in create project as the
       * source project to copy
       * </pre>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 5;</code>
       *
       * <pre>
       * this argument also is used in create project as the
       * source project to copy
       * </pre>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        name_ = value;
        onChanged();
        return this;
      }

      private long oneProjectId_ ;
      /**
       * <code>optional uint64 oneProjectId = 6;</code>
       *
       * <pre>
       * non-zero to open a specific project
       * </pre>
       */
      public boolean hasOneProjectId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional uint64 oneProjectId = 6;</code>
       *
       * <pre>
       * non-zero to open a specific project
       * </pre>
       */
      public long getOneProjectId() {
        return oneProjectId_;
      }
      /**
       * <code>optional uint64 oneProjectId = 6;</code>
       *
       * <pre>
       * non-zero to open a specific project
       * </pre>
       */
      public Builder setOneProjectId(long value) {
        bitField0_ |= 0x00000020;
        oneProjectId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 oneProjectId = 6;</code>
       *
       * <pre>
       * non-zero to open a specific project
       * </pre>
       */
      public Builder clearOneProjectId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        oneProjectId_ = 0L;
        onChanged();
        return this;
      }

      private boolean readOnly_ ;
      /**
       * <code>optional bool readOnly = 20;</code>
       */
      public boolean hasReadOnly() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bool readOnly = 20;</code>
       */
      public boolean getReadOnly() {
        return readOnly_;
      }
      /**
       * <code>optional bool readOnly = 20;</code>
       */
      public Builder setReadOnly(boolean value) {
        bitField0_ |= 0x00000040;
        readOnly_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool readOnly = 20;</code>
       */
      public Builder clearReadOnly() {
        bitField0_ = (bitField0_ & ~0x00000040);
        readOnly_ = false;
        onChanged();
        return this;
      }

      private long duedate_ ;
      /**
       * <code>optional uint64 duedate = 21;</code>
       *
       * <pre>
       * Date when the project is due 0 = never due
       * </pre>
       */
      public boolean hasDuedate() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional uint64 duedate = 21;</code>
       *
       * <pre>
       * Date when the project is due 0 = never due
       * </pre>
       */
      public long getDuedate() {
        return duedate_;
      }
      /**
       * <code>optional uint64 duedate = 21;</code>
       *
       * <pre>
       * Date when the project is due 0 = never due
       * </pre>
       */
      public Builder setDuedate(long value) {
        bitField0_ |= 0x00000080;
        duedate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 duedate = 21;</code>
       *
       * <pre>
       * Date when the project is due 0 = never due
       * </pre>
       */
      public Builder clearDuedate() {
        bitField0_ = (bitField0_ & ~0x00000080);
        duedate_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object displayprojectname_ = "";
      /**
       * <code>optional string displayprojectname = 22;</code>
       *
       * <pre>
       * or not an assignment
       * </pre>
       */
      public boolean hasDisplayprojectname() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string displayprojectname = 22;</code>
       *
       * <pre>
       * or not an assignment
       * </pre>
       */
      public java.lang.String getDisplayprojectname() {
        java.lang.Object ref = displayprojectname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            displayprojectname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string displayprojectname = 22;</code>
       *
       * <pre>
       * or not an assignment
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDisplayprojectnameBytes() {
        java.lang.Object ref = displayprojectname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          displayprojectname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string displayprojectname = 22;</code>
       *
       * <pre>
       * or not an assignment
       * </pre>
       */
      public Builder setDisplayprojectname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        displayprojectname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string displayprojectname = 22;</code>
       *
       * <pre>
       * or not an assignment
       * </pre>
       */
      public Builder clearDisplayprojectname() {
        bitField0_ = (bitField0_ & ~0x00000100);
        displayprojectname_ = getDefaultInstance().getDisplayprojectname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string displayprojectname = 22;</code>
       *
       * <pre>
       * or not an assignment
       * </pre>
       */
      public Builder setDisplayprojectnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        displayprojectname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object displayaccountname_ = "";
      /**
       * <code>optional string displayaccountname = 23;</code>
       *
       * <pre>
       * User name to display instead of email address
       * </pre>
       */
      public boolean hasDisplayaccountname() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string displayaccountname = 23;</code>
       *
       * <pre>
       * User name to display instead of email address
       * </pre>
       */
      public java.lang.String getDisplayaccountname() {
        java.lang.Object ref = displayaccountname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            displayaccountname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string displayaccountname = 23;</code>
       *
       * <pre>
       * User name to display instead of email address
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDisplayaccountnameBytes() {
        java.lang.Object ref = displayaccountname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          displayaccountname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string displayaccountname = 23;</code>
       *
       * <pre>
       * User name to display instead of email address
       * </pre>
       */
      public Builder setDisplayaccountname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        displayaccountname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string displayaccountname = 23;</code>
       *
       * <pre>
       * User name to display instead of email address
       * </pre>
       */
      public Builder clearDisplayaccountname() {
        bitField0_ = (bitField0_ & ~0x00000200);
        displayaccountname_ = getDefaultInstance().getDisplayaccountname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string displayaccountname = 23;</code>
       *
       * <pre>
       * User name to display instead of email address
       * </pre>
       */
      public Builder setDisplayaccountnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        displayaccountname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object backpackid_ = "";
      /**
       * <code>optional string backpackid = 24;</code>
       *
       * <pre>
       * accounts created by the HK portal have "ugly" account
       * names, so they provide something "better" to display instead
       * </pre>
       */
      public boolean hasBackpackid() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional string backpackid = 24;</code>
       *
       * <pre>
       * accounts created by the HK portal have "ugly" account
       * names, so they provide something "better" to display instead
       * </pre>
       */
      public java.lang.String getBackpackid() {
        java.lang.Object ref = backpackid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            backpackid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string backpackid = 24;</code>
       *
       * <pre>
       * accounts created by the HK portal have "ugly" account
       * names, so they provide something "better" to display instead
       * </pre>
       */
      public com.google.protobuf.ByteString
          getBackpackidBytes() {
        java.lang.Object ref = backpackid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          backpackid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string backpackid = 24;</code>
       *
       * <pre>
       * accounts created by the HK portal have "ugly" account
       * names, so they provide something "better" to display instead
       * </pre>
       */
      public Builder setBackpackid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        backpackid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string backpackid = 24;</code>
       *
       * <pre>
       * accounts created by the HK portal have "ugly" account
       * names, so they provide something "better" to display instead
       * </pre>
       */
      public Builder clearBackpackid() {
        bitField0_ = (bitField0_ & ~0x00000400);
        backpackid_ = getDefaultInstance().getBackpackid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string backpackid = 24;</code>
       *
       * <pre>
       * accounts created by the HK portal have "ugly" account
       * names, so they provide something "better" to display instead
       * </pre>
       */
      public Builder setBackpackidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        backpackid_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tokens.token)
    }

    static {
      defaultInstance = new token(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tokens.token)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tokens_token_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tokens_token_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013token.proto\022\006tokens\"\354\002\n\005token\022*\n\007comma" +
      "nd\030\001 \002(\0162\031.tokens.token.CommandType\022\n\n\002t" +
      "s\030\002 \001(\004\022\014\n\004uuid\030\003 \001(\t\022\021\n\tprojectid\030\004 \001(\004" +
      "\022\014\n\004name\030\005 \001(\t\022\024\n\014oneProjectId\030\006 \001(\004\022\020\n\010" +
      "readOnly\030\024 \001(\010\022\017\n\007duedate\030\025 \001(\004\022\032\n\022displ" +
      "ayprojectname\030\026 \001(\t\022\032\n\022displayaccountnam" +
      "e\030\027 \001(\t\022\022\n\nbackpackid\030\030 \001(\t\"w\n\013CommandTy" +
      "pe\022\014\n\010SSOLOGIN\020\000\022\017\n\013SHOWPROJECT\020\001\022\021\n\rCRE" +
      "ATEACCOUNT\020\002\022\021\n\rCREATEPROJECT\020\003\022\n\n\006LOGOU" +
      "T\020\004\022\r\n\tSSOLOGIN2\020\005\022\010\n\004NOOP\020\024B2\n$com.goog",
      "le.appinventor.server.tokensB\nTokenProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tokens_token_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tokens_token_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tokens_token_descriptor,
        new java.lang.String[] { "Command", "Ts", "Uuid", "Projectid", "Name", "OneProjectId", "ReadOnly", "Duedate", "Displayprojectname", "Displayaccountname", "Backpackid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
